#!/usr/bin/env python3
"""Generate the OpenVINO 2.0 C API symbol table used by FFmpeg's dlopen loader.

FFmpeg's OpenVINO DNN backend normally links against libopenvino_c at build
time.  OpenVINO encodes its release into the SONAME (libopenvino_c.so.2630 for
2026.3.0), so a link-time dependency forces an FFmpeg rebuild for every single
OpenVINO release, and makes OpenVINO a hard runtime dependency of FFmpeg.

Building with ``--enable-libopenvino-dlopen`` instead resolves the C API at
runtime via dlopen(), which lets the conda package demote OpenVINO to a
``run_constrained`` entry.  That needs a table of every ov_* function the
backend calls, together with its exact prototype.  Rather than hand-maintaining
~60 signatures, this script derives them from the OpenVINO headers we are
actually compiling against, so the table can never drift out of sync.

The emitted header is consumed twice by dnn_backend_openvino.c: once to declare
the function pointers, and once to redirect the existing call sites onto them.
"""

import argparse
import glob
import os
import re
import sys

# OPENVINO_C_API(<return type>) <name>(<params>);  --  possibly split over lines.
DECL_RE = re.compile(
    r'OPENVINO_C_API\(\s*([^)]*?)\s*\)\s*([A-Za-z_]\w*)\s*\((.*?)\)\s*;', re.S)

# Any ov_foo( appearing in the backend is a call we have to be able to resolve.
CALL_RE = re.compile(r'\b(ov_[A-Za-z0-9_]+)\s*\(')

# ...unless the backend defines it itself, e.g. a static helper that happens to
# be named ov_something. Those must not be looked for in the OpenVINO headers.
LOCAL_DEF_RE = re.compile(r'^\s*static\s[^;{]*?\b(ov_[A-Za-z0-9_]+)\s*\(', re.M)

HEADER_TEMPLATE = """\
/*
 * OpenVINO 2.0 C API symbol table for the dlopen loader.
 *
 * This file is generated by recipe/symbol_generation/gen_openvino_syms.py
 * from the OpenVINO headers FFmpeg is compiled against -- do not edit.
 *
 * OpenVINO version: {version}
 *
 * This file is part of FFmpeg.
 *
 * FFmpeg is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * FFmpeg is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with FFmpeg; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA
 */

/*
 * OV_SYM(return type, name, (parameter list))
 *
 * Include this file with OV_SYM defined to declare the function pointers or to
 * resolve them; include it with OV_SYM_REDIRECT defined to point the call sites
 * in dnn_backend_openvino.c at the loaded pointers.
 */

#ifdef OV_SYM
{sym_list}
#undef OV_SYM
#endif

#ifdef OV_SYM_REDIRECT
{redirects}
#undef OV_SYM_REDIRECT
#endif
"""


def openvino_version(include_dir):
    """Read OPENVINO_VERSION_* out of the C++ version header, if present."""
    path = os.path.join(include_dir, 'openvino', 'core', 'version.hpp')
    parts = []
    try:
        src = open(path, encoding='utf-8').read()
    except OSError:
        return 'unknown'
    for field in ('MAJOR', 'MINOR', 'PATCH'):
        m = re.search(r'#\s*define\s+OPENVINO_VERSION_%s\s+(\d+)' % field, src)
        if not m:
            return 'unknown'
        parts.append(m.group(1))
    return '.'.join(parts)


def strip_comments(src):
    src = re.sub(r'/\*.*?\*/', ' ', src, flags=re.S)
    return re.sub(r'//[^\n]*', ' ', src)


def collect_declarations(include_dir):
    """Map every exported ov_* function in the C API to (return type, params)."""
    decls = {}
    pattern = os.path.join(include_dir, 'openvino', 'c', '**', '*.h')
    headers = glob.glob(pattern, recursive=True)
    if not headers:
        sys.exit('error: no OpenVINO C API headers found under %s' % include_dir)
    for path in sorted(headers):
        src = strip_comments(open(path, encoding='utf-8').read())
        for ret, name, params in DECL_RE.findall(src):
            decls[name] = (ret, ' '.join(params.split()))
    return decls


def collect_used_symbols(backend_source):
    src = strip_comments(open(backend_source, encoding='utf-8').read())
    return set(CALL_RE.findall(src)) - set(LOCAL_DEF_RE.findall(src))


def main():
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument('--include-dir', required=True,
                   help='directory holding openvino/c/openvino.h')
    p.add_argument('--backend-source', required=True,
                   help='path to libavfilter/dnn/dnn_backend_openvino.c')
    p.add_argument('--output', required=True,
                   help='header file to write')
    args = p.parse_args()

    decls = collect_declarations(args.include_dir)
    used = collect_used_symbols(args.backend_source)

    # ov_* identifiers that are not exported functions (struct tags, enum
    # values, local helpers) are not our business; anything the backend calls
    # that we cannot resolve is, because it would fail to link at runtime.
    resolvable = sorted(used & set(decls))
    missing = sorted(name for name in used - set(decls)
                     if not name.endswith('_t'))
    if missing:
        sys.exit('error: called but not declared in the OpenVINO headers: %s'
                 % ', '.join(missing))
    if not resolvable:
        sys.exit('error: no OpenVINO symbols detected in %s' % args.backend_source)

    sym_list = '\n'.join(
        'OV_SYM(%s, %s, (%s))' % (decls[n][0], n, decls[n][1])
        for n in resolvable)
    redirects = '\n'.join('#define %s ff_%s' % (n, n) for n in resolvable)

    text = HEADER_TEMPLATE.format(
        version=openvino_version(args.include_dir),
        sym_list=sym_list,
        redirects=redirects)

    with open(args.output, 'w', encoding='utf-8') as fh:
        fh.write(text)
    print('generated %s (%d symbols, OpenVINO %s)'
          % (args.output, len(resolvable), openvino_version(args.include_dir)))


if __name__ == '__main__':
    main()
